### PR TITLE
an error when nShifts == 0

### PR DESCRIPTION
**Pull request by kfuku52**
Hi, I found that estimate_shift_configuration() got an error due to the undefined variable "shift.means", when no shift is detected. So I put NA in it if nShifts is 0. -Kenji

### CODE REVIEW

**Comment by cecileane** [comment]
Thanks for the bug report and fix! Perhaps it would be best to use a vector of length 0 rather than a missing value, i.e. `shift.means = c()` instead of `shift.means=NA`. One advantage would be that its length would be 0, (= number of shifts, like in other situations), instead of 1. What do you all think?

**Comment by kfuku52** [comment]
That would be more consistent. Please fell free to modify the pull request.

**Comment by cecileane** [comment]
I can't edit your pull request directly, Kenji. For this, the pull request should come from a branch other than your master branch (I think), and you would need to give one of us permission to push commits to your branch --see [here](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/). Or if there is another way, I'd love to learn how.

**Comment by kfuku52** [comment]
Sorry, I'm not familiar with the github system. I have just modified my master branch (shift.means = c() instead of shift.means=NA). If it does not work, I will create a branch later as you suggested.

**Comment by cecileane** [comment]
That was fast (especially today)! Many thanks for your contribution, @kfuku52.
@khabbazian: things looks great to me for a merge. (you could "squash" the commits, if github gives you the option: they are all about the same change).

**Comment by khabbazian** [comment]
Thank you! I merged the changes.

**Pull request merged**
